In [3]:
import os
import pandas as pd

dados_trimestrais_df = pd.read_csv("../data/meios_pagamentos_trimestral_2023_2025.csv")

print(dados_trimestrais_df.columns)
dados_trimestrais_df.head()

Index(['datatrimestre', 'valorPix', 'valorCartaoCredito', 'valorCartaoDebito',
       'valorTransIntrabancaria', 'quantidadePix', 'quantidadeCartaoCredito',
       'quantidadeCartaoDebito', 'quantidadeSaques'],
      dtype='object')

,datatrimestre,valorPix,valorCartaoCredito,valorCartaoDebito,valorTransIntrabancaria,quantidadePix,quantidadeCartaoCredito,quantidadeCartaoDebito,quantidadeSaques
0,2025-03-31,7472950.06,688902.63,233593.39,5100334.56,17540037.67,5145892.84,3972097.99,602547.75
1,2024-12-31,7714125.44,729052.42,259929.79,6924434.81,17960834.89,5356879.11,4282401.27,658974.39
2,2024-09-30,6976429.47,663265.83,241932.98,6669023.12,16546427.27,5042488.48,4121806.10,664226.23
3,2024-06-30,6284296.05,631782.08,239101.56,6164766.38,15356890.92,4879667.10,4057958.85,698603.67
4,2024-03-31,5429305.43,607468.54,235111.60,5376865.70,13575455.59,4723432.62,3952365.16,683039.52

#### Conferindo valores nulos

In [6]:
print("Valores nulos por coluna:")
print(dados_trimestrais_df.isnull().sum())

🔎 Valores nulos por coluna:
trimestre                    0
valor_pix                    0
valor_cartao_credito         0
valor_cartao_debito          0
valor_trans_intrabancaria    0
qtd_pix                      0
qtd_cartao_credito           0
qtd_cartao_debito            0
qtd_saques                   0
dtype: int64

### Tipos de Dados e Conversão

. Garantir que os dados estejam no formato correto é essencial para análises e manipulações futuras.

. trimestre como string: Facilita operações de filtragem e ordenação, evitando confusão com formatos de data ou números inteiros.

. Colunas numéricas como float: Garante que cálculos estatísticos, somas, médias e visualizações funcionem corretamente. Valores inválidos são convertidos em NaN para identificar possíveis problemas nos dados.

In [8]:
dados_trimestrais_df["trimestre"] = dados_trimestrais_df["trimestre"].astype(str)

colunas_numericas = [col for col in dados_trimestrais_df.columns if col != "trimestre"]

for col in colunas_numericas:
    dados_trimestrais_df[col] = pd.to_numeric(dados_trimestrais_df[col], errors="coerce")

print(dados_trimestrais_df.dtypes)
dados_trimestrais_df.head()

trimestre                     object
valor_pix                    float64
valor_cartao_credito         float64
valor_cartao_debito          float64
valor_trans_intrabancaria    float64
qtd_pix                      float64
qtd_cartao_credito           float64
qtd_cartao_debito            float64
qtd_saques                   float64
dtype: object

,trimestre,valor_pix,valor_cartao_credito,valor_cartao_debito,valor_trans_intrabancaria,qtd_pix,qtd_cartao_credito,qtd_cartao_debito,qtd_saques
0,2025-03-31,7472950.06,688902.63,233593.39,5100334.56,17540037.67,5145892.84,3972097.99,602547.75
1,2024-12-31,7714125.44,729052.42,259929.79,6924434.81,17960834.89,5356879.11,4282401.27,658974.39
2,2024-09-30,6976429.47,663265.83,241932.98,6669023.12,16546427.27,5042488.48,4121806.10,664226.23
3,2024-06-30,6284296.05,631782.08,239101.56,6164766.38,15356890.92,4879667.10,4057958.85,698603.67
4,2024-03-31,5429305.43,607468.54,235111.60,5376865.70,13575455.59,4723432.62,3952365.16,683039.52

#### Renomeando colunas e padronizando todas para snake_case

In [4]:
dados_trimestrais_df = dados_trimestrais_df.rename(columns={
    "datatrimestre": "trimestre",
    "valorPix": "valor_pix",
    "valorTED": "valor_ted",
    "valorTEC": "valor_tec",
    "valorCheque": "valor_cheque",
    "valorBoleto": "valor_boleto",
    "valorDOC": "valor_doc",
    "valorCartaoCredito": "valor_cartao_credito",
    "valorCartaoDebito": "valor_cartao_debito",
    "valorCartaoPrePago": "valor_cartao_pre_pago",
    "valorTransIntrabancaria": "valor_trans_intrabancaria",
    "valorConvenios": "valor_convenios",
    "valorDebitoDireto": "valor_debito_direto",
    "valorSaques": "valor_saques",
    "quantidadePix": "qtd_pix",
    "quantidadeTED": "qtd_ted",
    "quantidadeTEC": "qtd_tec",
    "quantidadeCheque": "qtd_cheque",
    "quantidadeBoleto": "qtd_boleto",
    "quantidadeDOC": "qtd_doc",
    "quantidadeCartaoCredito": "qtd_cartao_credito",
    "quantidadeCartaoDebito": "qtd_cartao_debito",
    "quantidadeCartaoPrePago": "qtd_cartao_pre_pago",
    "quantidadeTransIntrabancaria": "qtd_trans_intrabancaria",
    "quantidadeConvenios": "qtd_convenios",
    "quantidadeDebitoDireto": "qtd_debito_direto",
    "quantidadeSaques": "qtd_saques"
})

dados_trimestrais_df.head()

,trimestre,valor_pix,valor_cartao_credito,valor_cartao_debito,valor_trans_intrabancaria,qtd_pix,qtd_cartao_credito,qtd_cartao_debito,qtd_saques
0,2025-03-31,7472950.06,688902.63,233593.39,5100334.56,17540037.67,5145892.84,3972097.99,602547.75
1,2024-12-31,7714125.44,729052.42,259929.79,6924434.81,17960834.89,5356879.11,4282401.27,658974.39
2,2024-09-30,6976429.47,663265.83,241932.98,6669023.12,16546427.27,5042488.48,4121806.10,664226.23
3,2024-06-30,6284296.05,631782.08,239101.56,6164766.38,15356890.92,4879667.10,4057958.85,698603.67
4,2024-03-31,5429305.43,607468.54,235111.60,5376865.70,13575455.59,4723432.62,3952365.16,683039.52

In [9]:
dados_trimestrais_df.to_csv("../outputs/meios_pagamentos_trimestral_tratados.csv", index=False, encoding="utf-8-sig")

dados_trimestrais_df.to_json("../outputs/meios_pagamentos_trimestral_tratados.json", orient="records", force_ascii=False, indent=4)

print("Arquivos consolidados e tratados salvos em ../outputs/")

Arquivos consolidados e tratados salvos em ../outputs/